export const PATH = {
    home: '/',
    login: '/login',
    register: '/register',
    roomlist: '/roomlist',
    details: '/details',
    admin: '/admin',
    payment: '/payment',
    user: '/userinfo',
    editprofile: '/userinfo/editprofile',
    quanlydatphong: '/admin/quanlydatphong',
    quanlynguoidung: '/admin/quanlynguoidung',
    themnguoidung: '/admin/quanlynguoidung/themnguoidung',
    editNguoiDung: '/admin/quanlynguoidung/editnguoidung',
    quanlythongtinphong: '/admin/quanlythongtinphong',
    editphong:'/admin/quanlythongtinphong/editphong',
    themphong:'/admin/quanlythongtinphong/themphong',
    quanlythongtinvitri: '/admin/quanlythongtinvitri',
    themvitri: '/admin/quanlythongtinvitri/themvitri',
    editvitri: '/admin/quanlythongtinvitri/editvitri'
}